package promptrepo

import (
	"bytes"
	"encoding/json"
	"io"
	"path"
	"strings"
	"unicode/utf8"
)

const maxUITemplateFileDescriptorBytesV1 = 256 << 10

// UITemplateFileDescriptorV1 is a body-free filesystem companion generated by
// an owning CLI/application service. It may be serialized safely; source body
// bytes remain in their bounded HTML and CSS files.
type UITemplateFileDescriptorV1 struct {
	SchemaVersion string                      `json:"schema_version" yaml:"schema_version"`
	Address       UITemplateAddress           `json:"address" yaml:"address"`
	HTMLPath      string                      `json:"html_path" yaml:"html_path"`
	CSSPath       string                      `json:"css_path" yaml:"css_path"`
	Slots         []UITemplateSlotV1          `json:"slots,omitempty" yaml:"slots,omitempty"`
	Security      UITemplateSecurityProfileV1 `json:"security" yaml:"security"`
	Limits        UITemplateLimitsV1          `json:"limits" yaml:"limits"`
	HTMLBytes     int                         `json:"html_bytes" yaml:"html_bytes"`
	CSSBytes      int                         `json:"css_bytes" yaml:"css_bytes"`
	BodyBytes     int                         `json:"body_bytes" yaml:"body_bytes"`
	ContentDigest string                      `json:"content_digest" yaml:"content_digest"`
	Snapshot      string                      `json:"snapshot" yaml:"snapshot"`
}

func DecodeUITemplateFileDescriptorV1(payload []byte) (UITemplateFileDescriptorV1, error) {
	if len(payload) > maxUITemplateFileDescriptorBytesV1 || !utf8.Valid(payload) {
		return UITemplateFileDescriptorV1{}, NewError(CodeUITemplateLimitExceeded, "UI template descriptor must be bounded valid UTF-8 JSON", false, nil)
	}
	if _, err := decodeStrictJSON(payload, 32); err != nil {
		return UITemplateFileDescriptorV1{}, NewError(CodeUITemplateAddressInvalid, "UI template descriptor JSON is invalid", false, err)
	}
	var descriptor UITemplateFileDescriptorV1
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&descriptor); err != nil {
		return UITemplateFileDescriptorV1{}, NewError(CodeUITemplateAddressInvalid, "UI template descriptor is invalid", false, err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		return UITemplateFileDescriptorV1{}, NewError(CodeUITemplateAddressInvalid, "UI template descriptor has trailing JSON data", false, err)
	}
	if err := ValidateUITemplateFileDescriptorV1(descriptor); err != nil {
		return UITemplateFileDescriptorV1{}, err
	}
	return descriptor, nil
}

func ValidateUITemplateFileDescriptorV1(descriptor UITemplateFileDescriptorV1) error {
	if descriptor.SchemaVersion != UITemplateSchemaVersionV1 {
		return NewError(CodeUITemplateAddressInvalid, "UI template descriptor schema version is unsupported", false, nil)
	}
	if err := ValidateUITemplateAddress(descriptor.Address); err != nil {
		return err
	}
	if descriptor.Address.Role == "" || descriptor.Address.Path == "" || descriptor.Address.Digest == "" || descriptor.Address.Snapshot == "" {
		return NewError(CodeUITemplateAddressInvalid, "UI template descriptor requires an exact address", false, nil)
	}
	if descriptor.HTMLPath != descriptor.Address.Path || !safeUITemplatePath(descriptor.HTMLPath) || !strings.HasSuffix(strings.ToLower(descriptor.HTMLPath), ".html") {
		return NewError(CodeUITemplateAddressInvalid, "UI template descriptor HTML path is invalid", false, nil)
	}
	if !safeUITemplatePath(descriptor.CSSPath) || !strings.HasSuffix(strings.ToLower(descriptor.CSSPath), ".css") {
		return NewError(CodeUITemplateAddressInvalid, "UI template descriptor CSS path is invalid", false, nil)
	}
	if !sha256DigestPattern.MatchString(descriptor.ContentDigest) || descriptor.ContentDigest != descriptor.Address.Digest {
		return NewError(CodeUITemplateDigestMismatch, "UI template descriptor content digest binding is invalid", false, nil)
	}
	if !sha256DigestPattern.MatchString(descriptor.Snapshot) || descriptor.Snapshot != descriptor.Address.Snapshot {
		return NewError(CodeUITemplateSnapshotMismatch, "UI template descriptor snapshot binding is invalid", false, nil)
	}
	if descriptor.Security != UITemplateSecurityStaticReviewFragmentV1 {
		return NewError(CodeUITemplateHTMLForbidden, "UI template descriptor security profile is unsupported", false, nil)
	}
	if descriptor.HTMLBytes < 0 || descriptor.CSSBytes < 0 || descriptor.BodyBytes != descriptor.HTMLBytes+descriptor.CSSBytes {
		return NewError(CodeUITemplateLimitExceeded, "UI template descriptor body sizes are invalid", false, nil)
	}
	if err := validateUITemplateLimits(descriptor.Limits, descriptor.HTMLBytes, descriptor.CSSBytes, len(descriptor.Slots)); err != nil {
		return err
	}
	return validateUITemplateSlots(descriptor.Slots, descriptor.Limits)
}

// UITemplateFileDescriptorPath derives <base>.ui-template.json from the exact
// relative HTML path. It never introduces an absolute consumer path.
func UITemplateFileDescriptorPath(address UITemplateAddress) (string, error) {
	if err := ValidateUITemplateAddress(address); err != nil {
		return "", err
	}
	if address.Path == "" || !strings.HasSuffix(strings.ToLower(address.Path), ".html") {
		return "", NewError(CodeUITemplateAddressInvalid, "UI template HTML path is required", false, nil)
	}
	extension := path.Ext(address.Path)
	return strings.TrimSuffix(address.Path, extension) + ".ui-template.json", nil
}

func (descriptor UITemplateFileDescriptorV1) Bundle(htmlFragment, css []byte) UITemplateBundleV1 {
	return UITemplateBundleV1{
		SchemaVersion: descriptor.SchemaVersion,
		Address:       descriptor.Address,
		HTMLFragment:  append([]byte(nil), htmlFragment...),
		CSS:           append([]byte(nil), css...),
		Slots:         append([]UITemplateSlotV1(nil), descriptor.Slots...),
		Security:      descriptor.Security,
		Limits:        descriptor.Limits,
		ContentDigest: descriptor.ContentDigest,
		Snapshot:      descriptor.Snapshot,
	}
}
